from django.urls import path
from . import views

urlpatterns =[
    path('', views.home_view, name='home'),
    path('search/', views.search_livestock, name='search_livestock'),
    path('livestock/', views.livestock_list_view, name='livestock'),
    path('cowlis/<str:species>/', views.livestock_type, name='cowlis'),
    path('goatlis/<str:species>/', views.livestock_type, name='goatlis'),
    path('sheeplis/<str:species>/', views.livestock_type, name='sheeplis'),
    path('buffalolis/<str:species>/', views.livestock_type, name='buffalolis'),
    path('henlis/<str:species>/', views.livestock_type, name='henlis'),
    path('oxlis/<str:species>/', views.livestock_type, name='oxlis'),
    path('homepetslis/<str:species>/', views.livestock_type, name='homepetslis'),
    path('addliv/', views.add_livestock, name='add_livestock'),
    path('viewdetails/<int:livestock_id>/', views.viewdetails_view, name='viewdetails'),
    path('updatestatus/<int:pk>/', views.update_livestock_status, name='updatestatus'),
    path('deletelivestock/<int:pk>/', views.deletelivestock, name='deletelivestock'),
    path('toggle-favorite/<int:livestock_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('myfavorites/', views.favorite_list, name='myfavorites'),
    path('favorites/', views.favorite_list, name='favorite_list'),
    path('favorites-count/', views.favorites_count, name='favorites_count'),
    path('blog/', views.blog_view, name='blog'),
    path('10things/', views.ten_things_view, name='10things'),
    path('health-guide/', views.health_guide_view, name='health_guide'),
    path('market-trends/', views.market_trends_view, name='market_trends'),
    path('digital-trading/', views.digital_trading_view, name='digital_trading'),
    path('farmer-story/', views.farmer_story_view, name='farmer_story'),
    path('qurbani-guide/', views.qurbani_guide_view, name='qurbani_guide'),
    path('contact/', views.contact_view, name='contact'),
    path('api/livestock/<int:livestock_id>/', views.get_livestock_details, name='api_livestock_details'),
    path('notifications/delete/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('notifications/', views.get_notifications, name='get_notifications'),
    path('notifications/mark/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
]
