# Generated by Django 4.2.7 on 2026-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='breed',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
