# Generated by Django 4.2.7 on 2026-04-19 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value should be positive.')]),
        ),
    ]
