# Generated by Django 4.2.7 on 2026-04-19 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_livestock_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value should be positive.')]),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Price should be positive.')]),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Value should be positive.')]),
        ),
    ]
