# Generated by Django 4.2.7 on 2026-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_livestock_age_alter_livestock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='species',
            field=models.CharField(choices=[('buffalo', 'Buffalo'), ('cow', 'Cow'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('ox', 'Ox'), ('chicken', 'Chicken'), ('home pets', 'Home Pets'), ('parrot', 'Parrot'), ('dog', 'Dog'), ('cat', 'Cat'), ('pigeon', 'Pigeon'), ('rabbit', 'Rabbit'), ('horse', 'Horse')], max_length=20),
        ),
    ]
