# Generated by Django 4.2.7 on 2026-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_livestock_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='species',
            field=models.CharField(choices=[('buffalo', 'Buffalo'), ('cow', 'Cow'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('ox', 'Ox'), ('chicken', 'Chicken'), ('home pets', 'Home Pets'), ('parrot', 'Parrot'), ('dog', 'Dog'), ('cat', 'Cat'), ('pigeon', 'Pigeon'), ('rabbit', 'Rabbit')], max_length=20),
        ),
    ]
